  requireLazy(["HasteSupportData"], function (m) {
                m.handle({ gkxData: { "708253": { result: false, hash: "AT5n4hBL3YTMnQWt01M" }, "996940": { result: false, hash: "AT7opYuEGy3sjG1adhc" }, "1263340": { result: false, hash: "AT5bwizWgDaFQudm05Q" } } });
            });
            requireLazy(["TimeSliceImpl", "ServerJS"], function (TimeSlice, ServerJS) {
                new ServerJS().handle({
                    define: [
                        ["CometPersistQueryParams", [], { relative: {}, domain: {} }, 6231],
                        ["CurrentAdAccountInitialData", [], { AD_ACCOUNT_ID: null }, 6828],
                        ["BigPipeExperiments", [], { link_images_to_pagelets: false, enable_bigpipe_plugins: false }, 907],
                        [
                            "BootloaderConfig",
                            [],
                            {
                                deferBootloads: false,
                                jsRetries: [200, 500],
                                jsRetryAbortNum: 2,
                                jsRetryAbortTime: 5,
                                silentDups: false,
                                hypStep4: false,
                                phdOn: false,
                                btCutoffIndex: 579,
                                fastPathForAlreadyRequired: false,
                                translationRetries: [200, 500],
                                translationRetryAbortNum: 3,
                                translationRetryAbortTime: 50,
                            },
                            329,
                        ],
                        ["CSSLoaderConfig", [], { timeout: 5000, modulePrefix: "BLCSS:", forcePollForBootloader: true, loadEventSupported: true }, 619],
                        ["CurrentCommunityInitialData", [], {}, 490],
                        [
                            "CurrentUserInitialData",
                            [],
                            {
                                ACCOUNT_ID: "0",
                                USER_ID: "0",
                                NAME: "",
                                SHORT_NAME: null,
                                IS_BUSINESS_PERSON_ACCOUNT: false,
                                HAS_SECONDARY_BUSINESS_PERSON: false,
                                IS_FACEBOOK_WORK_ACCOUNT: false,
                                IS_MESSENGER_ONLY_USER: false,
                                IS_DEACTIVATED_ALLOWED_ON_MESSENGER: false,
                                IS_MESSENGER_CALL_GUEST_USER: false,
                                IS_WORK_MESSENGER_CALL_GUEST_USER: false,
                                IS_WORKROOMS_USER: false,
                                APP_ID: "412378670482",
                                IS_BUSINESS_DOMAIN: false,
                            },
                            270,
                        ],
                        ["ErrorDebugHooks", [], { SnapShotHook: null }, 185],
                        ["ISB", [], {}, 330],
                        ["LSD", [], { token: "AVoD5kNm1Ug" }, 323],
                        [
                            "MRequestConfig",
                            [],
                            {
                                dtsg: { token: "NAcOM2CbO0QGUlpm8zos_qBWWdZ6L5jFSLyNMDozSaihC4jwJPLyEPQ:0:0", valid_for: 86400, expire: 1684321475 },
                                dtsg_ag: { token: "AQzy5Rqg_2tUgaiWWXhaTC0ybwIqeprS27lSdCvFhOBLOD-k:0:0", valid_for: 604800, expire: 1684839875 },
                                lsd: "AVoD5kNm1Ug",
                                checkResponseOrigin: true,
                                checkResponseToken: true,
                                cleanFinishedRequest: false,
                                cleanFinishedPrefetchRequests: false,
                                ajaxResponseToken: { secret: "FIx7hN89UMPoqd9w64biPmPesgZHK8jb", encrypted: "AYk4GEQtjKxzWF1sjAdC8nSEzptWmrj0Q3rGsxHiFf6GKWHRQooyapox6p7VtRpJmGiWxBbT-Qe2yqgXCPqrz5nuMeutp_jiDROOv7TZIxL4RQ" },
                            },
                            51,
                        ],
                        ["ServerNonce", [], { ServerNonce: "bjXZmCvxkuA1kKPFKyZpy2" }, 141],
                        [
                            "SiteData",
                            [],
                            {
                                server_revision: 1007500803,
                                client_revision: 1007500803,
                                tier: "",
                                push_phase: "C3",
                                pkg_cohort: "BP:m_kaios_pkg",
                                haste_session: "19493.BP:m_kaios_pkg.2.0..0.0",
                                pr: 1,
                                haste_site: "mobile",
                                manifest_base_uri: "https:\/\/z-m-static.xx.fbcdn.net",
                                manifest_origin: null,
                                manifest_version_prefix: null,
                                be_one_ahead: false,
                                is_rtl: false,
                                is_comet: false,
                                is_experimental_tier: false,
                                is_jit_warmed_up: true,
                                hsi: "7233734567751071683",
                                semr_host_bucket: "3",
                                bl_hash_version: 2,
                                skip_rd_bl: true,
                                comet_env: 0,
                                wbloks_env: false,
                                spin: 0,
                                __spin_r: 1007500803,
                                __spin_b: "trunk",
                                __spin_t: 1684235075,
                                vip: "102.132.101.35",
                            },
                            317,
                        ],
                        ["SprinkleConfig", [], { param_name: "jazoest", version: 2, should_randomize: false }, 2111],
                        ["PromiseUsePolyfillSetImmediateGK", [], { www_always_use_polyfill_setimmediate: false }, 2190],
                        [
                            "KSConfig",
                            [],
                            {
                                killed: {
                                    __set: [
                                        "MLHUB_FLOW_AUTOREFRESH_SEARCH",
                                        "NEKO_DISABLE_CREATE_FOR_SAP",
                                        "EO_DISABLE_SYSTEM_SERIAL_NUMBER_FREE_TYPING_IN_CPE_NON_CLIENT",
                                        "MOBILITY_KILL_OLD_VISIBILITY_POSITION_SETTING",
                                        "WORKPLACE_DISPLAY_TEXT_EVIDENCE_REPORTING",
                                        "BUSINESS_INVITE_FLOW_WITH_SELLER_PROFILE",
                                        "BUY_AT_UI_LINE_DELETE",
                                        "BUSINESS_GRAPH_SETTING_APP_ASSIGNED_USERS_NEW_API",
                                        "BUSINESS_GRAPH_SETTING_BU_ASSIGNED_USERS_NEW_API",
                                        "BUSINESS_GRAPH_SETTING_ESG_ASSIGNED_USERS_NEW_API",
                                        "BUSINESS_GRAPH_SETTING_PRODUCT_CATALOG_ASSIGNED_USERS_NEW_API",
                                        "BUSINESS_GRAPH_SETTING_SESG_ASSIGNED_USERS_NEW_API",
                                        "BUSINESS_GRAPH_SETTING_WABA_ASSIGNED_USERS_NEW_API",
                                        "ADS_PLACEMENT_FIX_PUBLISHER_PLATFORMS_MUTATION",
                                        "FORCE_FETCH_BOOSTED_COMPONENT_AFTER_ADS_CREATION",
                                        "VIDEO_DIMENSIONS_FROM_PLAYER_IN_UPLOAD_DIALOG",
                                        "SNIVY_GROUP_BY_EVENT_TRACE_ID_AND_NAME",
                                        "ADS_STORE_VISITS_METRICS_DEPRECATION",
                                        "AD_DRAFT_ENABLE_SYNCRHONOUS_FRAGMENT_VALIDATION",
                                        "SEPARATE_MESSAGING_COMACTIVITY_PAGE_PERMS",
                                        "LAB_NET_NEW_UI_RELEASE",
                                        "POCKET_MONSTERS_CREATE",
                                        "POCKET_MONSTERS_DELETE",
                                        "WORKPLACE_PLATFORM_SECURE_APPS_MAILBOXES",
                                        "POCKET_MONSTERS_UPDATE_NAME",
                                        "IC_DISABLE_MERGE_TOOL_FEED_CHECK_FOR_REPLACE_SCHEDULE",
                                        "ADS_EPD_IMPACTED_ADVERTISER_MIGRATE_XCONTROLLER",
                                        "RECRUITING_CANDIDATE_PORTAL_ACCOUNT_DELETION_CARD",
                                        "BIZ_INBOX_POP_UP_TIP_NAVIGATION_BUG_FIX",
                                        "SRT_REVIEW_DISABLE_FELLOWSHIP_REVIEW",
                                        "EO_STORE_HOME_PAGE_COVID19_BANNER",
                                        "TPA_SRT_TRANSLATION",
                                    ],
                                },
                                ko: {
                                    __set: [
                                        "3OsLvnSHNTt",
                                        "1G7wJ6bJt9K",
                                        "9NpkGYwzrPG",
                                        "3oh5Mw86USj",
                                        "8NAceEy9JZo",
                                        "7FOIzos6XJX",
                                        "rf8JEPGgOi",
                                        "4j36SVzvP3w",
                                        "4NSq3ZC4ScE",
                                        "53gCxKq281G",
                                        "3yzzwBY7Npj",
                                        "1onzIv0jH6H",
                                        "8PlKuowafe8",
                                        "1ntjZ2zgf03",
                                        "4SIH2GRVX5W",
                                        "2dhqRnqXGLQ",
                                        "2WgiNOrHVuC",
                                        "amKHb4Cw4WI",
                                        "8rDvN9vWdAK",
                                        "5BdzWGmfvrA",
                                        "DDZhogI19W",
                                        "acrJTh9WGdp",
                                        "1oOE64fL4wO",
                                        "5XCz1h9Iaw3",
                                        "7r6mSP7ofr2",
                                        "6DGPLrRdyts",
                                        "aWxCyi1sEC7",
                                        "9kCSDzzr8fu",
                                        "awYA7fn2Bse",
                                        "aBMlJ8QRPWE",
                                        "Fl3bH3ozLe",
                                        "3sKizTQ6byg",
                                    ],
                                },
                            },
                            2580,
                        ],
                        [
                            "CurrentBusinessUser",
                            [],
                            {
                                business_id: null,
                                business_persona_id: null,
                                business_role: null,
                                business_user_id: null,
                                businessAccountName: null,
                                email: null,
                                first_name: null,
                                ip_permission: null,
                                isBusinessPerson: false,
                                isFacebookWorkAccount: false,
                                isInstagramBusinessPerson: false,
                                isEnterpriseBusiness: false,
                                shouldHideComponentsByUnsupportedFirstPartyTools: false,
                                shouldShowAccountSwitchComponents: false,
                                isUserOptInAccountSwitchInfraUpgrade: false,
                                business_profile_pic_url: null,
                                enterprise_profile_pic_url: null,
                                isTwoFacNewFlow: false,
                                last_name: null,
                                personal_user_id: "0",
                                is_ads_feature_limited: null,
                                is_business_banhammered: null,
                                expiry_time: null,
                                has_verified_email: null,
                                permitted_business_account_task_ids: [],
                            },
                            2654,
                        ],
                        ["JSErrorLoggingConfig", [], { appId: 412378670482, extra: [], reportInterval: 50, sampleWeight: null, sampleWeightKey: "__jssesw", projectBlocklist: [] }, 2776],
                        ["ImmediateImplementationExperiments", [], { prefer_message_channel: true }, 3419],
                        [
                            "UriNeedRawQuerySVConfig",
                            [],
                            {
                                uris: [
                                    "dms.netmng.com",
                                    "doubleclick.net",
                                    "r.msn.com",
                                    "watchit.sky.com",
                                    "graphite.instagram.com",
                                    "www.kfc.co.th",
                                    "learn.pantheon.io",
                                    "www.landmarkshops.in",
                                    "www.ncl.com",
                                    "s0.wp.com",
                                    "www.tatacliq.com",
                                    "bs.serving-sys.com",
                                    "kohls.com",
                                    "lazada.co.th",
                                    "xg4ken.com",
                                    "technopark.ru",
                                    "officedepot.com.mx",
                                    "bestbuy.com.mx",
                                    "booking.com",
                                    "nibio.no",
                                ],
                            },
                            3871,
                        ],
                        ["RunGatingConfig", [], { shouldUseBrowserUnload: true }, 3914],
                        ["InitialCookieConsent", [], { deferCookies: false, initialConsent: [1, 2], noCookies: false, shouldShowCookieBanner: false }, 4328],
                        ["WebConnectionClassServerGuess", [], { connectionClass: "GOOD" }, 4705],
                        ["BootloaderEndpointConfig", [], { debugNoBatching: false, maxBatchSize: -1, endpointURI: "https:\/\/m.facebook.com\/ajax\/bootloader-endpoint\/" }, 5094],
                        ["CookieConsentIFrameConfig", [], { consent_param: "FQAREhISAA==.ARYfvh-KJAs2QAruIFaJY-alntyMQKGA2wo2ne_e9sc1uLem", allowlisted_iframes: [] }, 5540],
                        ["cr:1126", ["TimeSliceImpl"], { __rc: ["TimeSliceImpl", "Aa2-0kJyLDztinVtjFWC2sBS6TcJYv93blQosvMjgbnR5AZY0SKRgyU5m-IUY1vIU0clITsL0EoVqIfBjtFEqc0"] }, -1],
                        ["cr:6640", ["PromiseImpl"], { __rc: ["PromiseImpl", "Aa37G1qbxZWUma9EM6jgCMiGLRnN86I1mTsCfyv20RVpzy0NMaKihWzACBKc5JACn1I92Wqn_gVEyX4yDTNKvhcGIqEotA"] }, -1],
                        ["cr:696703", [], { __rc: [null, "Aa3PUYuKrg75edWoVcHprzXiRX7oDYR8Yt3mMlJfCEPe0pr8QAfP9eIJ6SKJgeMFWOrxVbkvEWLBJ58CxezcVJIi088"] }, -1],
                    ],
                    require: [["MPrelude"]],
                });
            });