
            requireLazy(["__bigPipe"], function (bigPipe) {
                bigPipe.onPageletArrive({
                    id: "last_response",
                    phase: 63,
                    last_in_phase: true,
                    the_end: true,
                    jsmods: {
                        define: [
                            ["ChannelClientConfig", [], {}, 395],
                            ["MercuryConfig", [], {}, 35],
                            [
                                "MqttWebConfig",
                                [],
                                {
                                    fbid: "0",
                                    appID: 219994525426954,
                                    endpoint: "wss://edge-chat.facebook.com/chat",
                                    pollingEndpoint: "https://edge-chat.facebook.com/mqtt/pull",
                                    subscribedTopics: [],
                                    capabilities: 10,
                                    clientCapabilities: 3,
                                    chatVisibility: false,
                                    hostNameOverride: "",
                                },
                                3790,
                            ],
                            ["MqttPublishTimeoutConfig", [], { mqttPublishTimeoutMs: 90000 }, 4266],
                            [
                                "MobileWebMessageTypesSitevarConfig",
                                [],
                                {
                                    ChatProxySupportedMessageTypes: {
                                        __map: [
                                            ["anbox", true],
                                            ["chatproxy-presence", true],
                                            ["confirm_contactpoint", true],
                                            ["delta", true],
                                            ["deltaflow", true],
                                            ["deltaflowreject", true],
                                            ["friend_requests_seen", true],
                                            ["friending_state_change", true],
                                            ["inbox", true],
                                            ["jewel_friending_notifs", true],
                                            ["jewel_requests_add", true],
                                            ["jewel_requests_remove_old", true],
                                            ["live_poke", true],
                                            ["m_notification", true],
                                            ["mobile_requests_count", true],
                                            ["nav_update_counts", true],
                                            ["notifications_read", true],
                                            ["notifications_seen", true],
                                            ["onevc", true],
                                            ["privacy_changed", true],
                                            ["qprimer", true],
                                            ["skywalker", true],
                                            ["typ", true],
                                            ["webrtc", true],
                                        ],
                                    },
                                    MQTTMigrationExcludeMessageTypes: {
                                        __map: [
                                            ["anbox", true],
                                            ["chatproxy-presence", true],
                                            ["delta", true],
                                            ["deltaflow", true],
                                            ["deltaflowreject", true],
                                            ["onevc", true],
                                            ["qprimer", true],
                                            ["skywalker", true],
                                            ["typ", true],
                                            ["webrtc", true],
                                        ],
                                    },
                                },
                                4273,
                            ],
                            ["MqttWebDeviceID", [], { clientID: "c91b3e95-0901-401f-9f86-0d5df365983a" }, 5003],
                            ["IntlCurrentLocale", [], { code: "en_GB" }, 5954],
                            ["MLoginTopDomainsConfig", [], { topEmailDomains: ["gmail.com", "yahoo.com", "outlook.com", "yandex.com", "naij.com"] }, 6972],
                            ["USIDMetadata", [], { browser_id: "?", tab_id: "", page_id: "Prur03nmspgs1", transition_id: 0, version: 6 }, 5888],
                            ["BrowserPaymentHandlerConfig", [], { enabled: false }, 3904],
                            ["BrowserPushPubKey", [], { appServerKey: "BIBn3E_rWTci8Xn6P9Xj3btShT85Wdtne0LtwNUyRQ5XjFNkuTq9j4MPAVLvAFhXrUU1A9UxyxBA7YIOjqDIDHI" }, 4806],
                            ["MTouchableSyntheticClickGK", [], { USE_SYNTHETIC_CLICK: true }, 368],
                            ["cr:686", [], { __rc: [null, "Aa0r_DuEL91I2XT2VmyQ1wMYzQFFTTE0hWR3EHyawP-UldJzJhSkMMy5OV-1UNmy0EjoLBHVfvA3Qovg1SS9C5R6xA"] }, -1],
                            ["cr:1069930", [], { __rc: [null, "Aa3PUYuKrg75edWoVcHprzXiRX7oDYR8Yt3mMlJfCEPe0pr8QAfP9eIJ6SKJgeMFWOrxVbkvEWLBJ58CxezcVJIi088"] }, -1],
                            ["cr:1083116", ["XAsyncRequest"], { __rc: ["XAsyncRequest", "Aa3PUYuKrg75edWoVcHprzXiRX7oDYR8Yt3mMlJfCEPe0pr8QAfP9eIJ6SKJgeMFWOrxVbkvEWLBJ58CxezcVJIi088"] }, -1],
                            ["cr:1083117", [], { __rc: [null, "Aa3PUYuKrg75edWoVcHprzXiRX7oDYR8Yt3mMlJfCEPe0pr8QAfP9eIJ6SKJgeMFWOrxVbkvEWLBJ58CxezcVJIi088"] }, -1],
                            ["cr:1984081", [], { __rc: [null, "Aa24B5jGiIr1xiVQdHN7MYSCMoVKMNtf4yoVEc2LwGJ4NH7pdWtBp96sJCokaaCSoZAchRgGRWMMo3FroR9f2U6Ovy2U"] }, -1],
                            ["cr:334", ["ghlTestUBTFacebook"], { __rc: ["ghlTestUBTFacebook", "Aa3xVxVbWNgtBdXbDLl_-Oq-8jctl5DvI6UF0cdiyg3X41zNLq3ocb6Far5aW3zqnlv67x_WyHvn3agzgkCQi7sTyQ"] }, -1],
                            ["cr:1088657", [], { __rc: [null, "Aa0rZHVQGvwIvKIMsKJ8JB0eodSuACkjZO0B60GDNXBKK42JgCMSaWSRcbqm0KI1Bl54iAYY_8pwbSd8NYXgdyo"] }, -1],
                            ["cr:1543261", [], { __rc: [null, "Aa0OwEaAJM2WbQgzU0YF4wREmCDLSfs1OF-RQmSWOwNy3u4b4Bwex4Rm2WBgnYNFati-dMFoX7Jrq8iE_-gzw9LB"] }, -1],
                            ["cr:708886", ["EventProfilerImpl"], { __rc: ["EventProfilerImpl", "Aa3PUYuKrg75edWoVcHprzXiRX7oDYR8Yt3mMlJfCEPe0pr8QAfP9eIJ6SKJgeMFWOrxVbkvEWLBJ58CxezcVJIi088"] }, -1],
                            ["cr:1094907", [], { __rc: [null, "Aa2b0MKlr4HNZB4R16RM5CZZ1ZvxPz5Eguz2NwcFTN0Mct050xFPd1exyuA-xRkHZYtqzgmxnCBCJSli4isTzfs"] }, -1],
                            ["cr:5800", [], { __rc: [null, "Aa16Zw7UmvhUtW3lrqh6RNA3jeAEWcp97A9x5xj3lTftX6vxjhG4SE231XsbTwjSdsLim6eILB4JsANoBtXnrXmY9dY"] }, -1],
                            ["GhlTennisKnobsConfig", [], { ghlbox_log_validity_in_mins: 7200, ghlbox_initialize_in_mins: 14400, change_class_interval_in_mins: 1440 }, 6687],
                            [
                                "EventConfig",
                                [],
                                {
                                    sampling: {
                                        bandwidth: 0,
                                        play: 0,
                                        playing: 0,
                                        progress: 0,
                                        pause: 0,
                                        ended: 0,
                                        seeked: 0,
                                        seeking: 0,
                                        waiting: 0,
                                        loadedmetadata: 0,
                                        canplay: 0,
                                        selectionchange: 0,
                                        change: 0,
                                        timeupdate: 0,
                                        adaptation: 0,
                                        focus: 0,
                                        blur: 0,
                                        load: 0,
                                        error: 0,
                                        message: 0,
                                        abort: 0,
                                        storage: 0,
                                        scroll: 200000,
                                        mousemove: 20000,
                                        mouseover: 10000,
                                        mouseout: 10000,
                                        mousewheel: 1,
                                        MSPointerMove: 10000,
                                        keydown: 0.1,
                                        click: 0.02,
                                        mouseup: 0.02,
                                        __100ms: 0.001,
                                        __default: 5000,
                                        __min: 100,
                                        __interactionDefault: 200,
                                        __eventDefault: 100000,
                                    },
                                    page_sampling_boost: 1,
                                    interaction_regexes: {},
                                    interaction_boost: {},
                                    event_types: {},
                                    manual_instrumentation: false,
                                    profile_eager_execution: false,
                                    disable_heuristic: true,
                                    disable_event_profiler: false,
                                },
                                1726,
                            ],
                            ["MarauderConfig", [], { app_version: "1.0.0.0 (1007500803)", gk_enabled: false }, 31],
                            [
                                "SearchMTouchGlobalOptions",
                                [],
                                {
                                    enableSeeMore: true,
                                    enableQueryThrottle: true,
                                    queryThrottleTime: 125,
                                    queryWaitTime: 125,
                                    enableEagerSendRequest: true,
                                    useBanzaiLogging: false,
                                    redirectPages: false,
                                    noSnippet: false,
                                    defaultNumTopResultsToShow: 3,
                                    useNewTypeaheadPerfLogger: true,
                                    keywordsOnlyEnabled: true,
                                    prefixMatchEntityBootstrap: true,
                                    disableHighlighting: false,
                                },
                                344,
                            ],
                            [
                                "TimeSliceInteractionSV",
                                [],
                                {
                                    on_demand_reference_counting: true,
                                    on_demand_profiling_counters: true,
                                    default_rate: 1000,
                                    lite_default_rate: 100,
                                    interaction_to_lite_coinflip: { ADS_INTERFACES_INTERACTION: 0, ads_perf_scenario: 0, ads_wait_time: 0, Event: 10 },
                                    interaction_to_coinflip: { ADS_INTERFACES_INTERACTION: 1, ads_perf_scenario: 1, ads_wait_time: 1, Event: 500 },
                                    enable_heartbeat: true,
                                    maxBlockMergeDuration: 0,
                                    maxBlockMergeDistance: 0,
                                    enable_banzai_stream: true,
                                    user_timing_coinflip: 50,
                                    banzai_stream_coinflip: 0,
                                    compression_enabled: true,
                                    ref_counting_fix: false,
                                    ref_counting_cont_fix: false,
                                    also_record_new_timeslice_format: false,
                                    force_async_request_tracing_on: false,
                                },
                                2609,
                            ],
                            ["MBootstrapCacheMaxCacheTime", [], { maxCacheTimeByKey: { typeahead_facebar3: 1209600000, typeahead_search_bem3: 1209600000 } }, 2886],
                            [
                                "MSearchTypeaheadConfig",
                                [],
                                {
                                    sources: {
                                        bootstrapped: { src: "/typeahead/search/facebar/bootstrap/?filters%5B0%5D=keyword", source_key: "facebar3", max_results: 6 },
                                        nullstate: { src: "/typeahead/search/facebar/nullstate/", max_results: 20 },
                                        online: { src: "/typeahead/search/facebar/query/?context=facebar&grammar_version=bee09f93fa732cfa59a1cb6d9f450d3892424e49&viewer=0&rsp=search", max_results: 20, enable_caching: true },
                                    },
                                    typeaheadScubaInfo: null,
                                    disableLongerQueryCacheHit: true,
                                    compositeSourceConfig: {
                                        maxResults: 50,
                                        minCostForUserToSurfaceAtTop: 7,
                                        maxPositionOfEntityToDivideKeywords: 5,
                                        maxKeywordAboveEntities: 2,
                                        filterOutTypes: [],
                                        keepBootstrapped: true,
                                        enableLegacyStyleBucketization: true,
                                    },
                                    hasRecentSearches: false,
                                    numResultsToFetch: 13,
                                    initialNumRecentResultsToShow: 13,
                                    defaultNumTopResultsToShow: 3,
                                    keywordsOnlyEnabled: true,
                                    keywordBucketSize: 6,
                                },
                                4113,
                            ],
                        ],
                        require: [
                            [
                                "BDClientSignalCollectionTrigger",
                                "startSignalCollection",
                                [],
                                [
                                    {
                                        sc:
                                            '{"t":1659080345,"c":[[30000,838801],[30001,838801],[30002,838801],[30003,838801],[30004,838801],[30005,838801],[30006,573585],[30007,838801],[30008,838801],[30012,838801],[30013,838801],[30015,806033],[30018,806033],[30021,540823],[30022,540817],[30040,806033],[30093,806033],[30094,806033],[30095,806033],[30101,541591],[30102,541591],[30103,541591],[30104,541591],[30106,806039],[30107,806039],[38000,541427],[38001,806643]]}',
                                        fds: 60,
                                        fda: 60,
                                        i: 60,
                                        sbs: 1,
                                        dbs: 100,
                                        bbs: 100,
                                        hbi: 60,
                                        rt: 262144,
                                        hbcbc: 2,
                                        hbvbc: 0,
                                        hbbi: 30,
                                        sid: -1,
                                        hbv: "8497830978835245394",
                                    },
                                ],
                            ],
                            [
                                "NavigationMetrics",
                                "setPage",
                                [],
                                [{ page: "XLoginController", page_type: "normal", page_uri: "https://m.facebook.com/login.php?next=https%3A%2F%2Fm.facebook.com%2Fhome.php&refsrc=deprecated&_rdr", serverLID: "7233734567751071683" }],
                            ],
                            ["Artillery", "disable", [], []],
                            ["ServiceWorkerURLCleaner", "removeRedirectID", [], []],
                        ],
                    },
                    hsrp: {
                        hsdp: { clpData: { "1743095": { r: 1, s: 1 } }, gkxData: { "1652843": { result: false, hash: "AT6uh9NWRY4QEQoYnf0" } } },
                        hblp: {
                            consistency: { rev: 1007500803 },
                            rsrcMap: {
                                O7kNNP8: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yI/r/Ib90vcVxYzI.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                                zPYlTyl: { type: "js", src: "https://z-m-static.xx.fbcdn.net/rsrc.php/v3/yO/r/_tJ17sGyxOX.js?_nc_x=Ij3Wp8lg5Kz", nc: 1 },
                            },
                        },
                    },
                    allResources: ["O7kNNP8", "YR8dqzY", "zPYlTyl", "o0XrPfg", "+GFcllE"],
                });
            });